Started by user [8mha:////4DQFrxSfDlsc0AMNZpuSN+0X03cGwZ6761Sg3liq6yoIAAAAkh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLQIwSBnb90uLUIv0UAGZnkYG8AAAA[0md
Running as SYSTEM
Building in workspace /var/jenkins_home/workspace/backup
[backup] $ /bin/sh -xe /tmp/jenkins7435398684953065986.sh
+ cd /var/jenkins_home
+ BACKUP_TIME=
+ git config --global user.email dattatrey.ds@gmail.com
+ git config --global user.name dattatrey29
+ git init
Reinitialized existing Git repository in /var/jenkins_home/.git/
+ git add .
+ git commit -m backup-
[master d70c2a3] backup-
 9 files changed, 70 insertions(+), 12 deletions(-)
 create mode 100644 jobs/backup/builds/23/build.xml
 create mode 100644 jobs/backup/builds/24/changelog.xml
 create mode 100644 jobs/backup/builds/24/log
+ git remote set-url origin https://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@github.com/dattatrey29/jenkins_backup.git
+ git push -u origin master
To https://github.com/dattatrey29/jenkins_backup.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://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@github.com/dattatrey29/jenkins_backup.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Build step 'Execute shell' marked build as failure
Finished: FAILURE
